### ISSUE TITLE
Alt Text inside angle brackets doesn't render

### ISSUE THREAD

**Issue by ilyanep** [schmamps/angola-maldives#14]
Hello again!

I found a funny edge case with this comic: https://www.qwantz.com/index.php?comic=4192

The alt text is entirely in angle brackets, which I'm guessing is causing the text to render in a way that the browser parses as HTML. 

Not a big deal but figured I'd let you know haha.

**Comment by schmamps** [comment]
I see [the problem](https://github.com/schmamps/yu-dereader/blob/8d96577732b527282252118ffd50bb201b47a1d5/src/ts/lay/nest.ts#L12) and have a solution:

```ts
  const element = dom.create("span");

  element.textContent = contentVal;

  return element;
```

Building it is another story.

**Comment by schmamps** [comment]
Built and pushed!
